### ISSUE TITLE
Motion correction is performed twice

### ISSUE THREAD

**Issue by chrisgorgo** [preprocessed-connectomes-project/quality-assessment-protocol#10]
I was reading the code and it turns out that motion correction is performed twice (both of the times with "--twopass" argument so four times in total): https://github.com/preprocessed-connectomes-project/quality-assessment-protocol/blob/master/qap/functional_preproc.py#L160

It's not clear from the code or documentation why is this implemented this way.

**Comment by jpellman** [comment]
Hi Chris,

The code for the functional preprocessing is based off of C-PAC's.  Cameron's answer to the following question in the C-PAC issue tracker might help clarify the implementation:

https://github.com/FCP-INDI/C-PAC/issues/452

**Comment by sgiavasis** [comment]
We're changing this so that it only happens once. Changes are currently in branch 1.0.6_dev. (Really wish Github would let you tag branches in comments..)
