### ISSUE TITLE
calc_dvars crashes on many datasets

### ISSUE THREAD

**Issue by poldrack** [preprocessed-connectomes-project/quality-assessment-protocol#2]
hi - I am having a problem where calc_dvars crashes on more than 1/2 of my datasets (from the myconnectome project):

unning calc_dvars
Traceback (most recent call last):
  File "run_qap_func.py", line 53, in <module>
    func_dvars  = calc_dvars(func_data, output_all=False)
  File "/scratch/projects/UT/poldracklab/poldrack/selftracking/MRI/qatest/quality-assessment-protocol/qa
p/dvars.py", line 68, in calc_dvars
    func_ar1    = ar1(func)
  File "/scratch/projects/UT/poldracklab/poldrack/selftracking/MRI/qatest/quality-assessment-protocol/qa
p/dvars.py", line 60, in ar1
    ar_vals = np.apply_along_axis(method, 0, func_centered)
  File "/work/01329/poldrack/yye00/local/lib/python2.7/site-packages/numpy/lib/shape_base.py", line 96,
in apply_along_axis
    res = func1d(arr[tuple(i.tolist())],*args)
  File "/scratch/projects/UT/poldracklab/poldrack/selftracking/MRI/qatest/quality-assessment-protocol/qa
p/dvars.py", line 47, in ar_nitime
    ak  = linalg.solve(Tm, y)
  File "/work/01329/poldrack/yye00/local/lib/python2.7/site-packages/scipy/linalg/basic.py", line 100, i
n solve
    raise LinAlgError("singular matrix")
numpy.linalg.linalg.LinAlgError: singular matrix

Chris G said he has encountered the same errors.

**Comment by ccraddock** [comment]
Hey Russ,

I just merged some of Chris's changes to QAP today. Do you have the problem with these as well? 

-cc

**Comment by ccraddock** [comment]
Never mind, I suspect that it will still happen, considering calc_dvars wasn't touched by Chris's pull request. We will look this over and get back to you soon.

**Comment by poldrack** [comment]
Thanks! Yes, I was using Chris's latest

**Comment by sgiavasis** [comment]
Hi Dr. Poldrack,

After looking over the QAP code with Cameron, we suspect the functional mask was including voxels with timeseries that had zero variance, which would then trip up the matrix inversion down the line. I've added a check which might solve your problem.

Try pulling the repo one more time and re-installing, and give it a shot.

If it still crashes, let us know and we'll continue to work towards a solution this week.

-Steve Giavasis

**Comment by sgiavasis** [comment]
As this error has not been seen, and we believe the aforementioned fix most likely would have addressed it, I am closing this issue for now. If it recurs we can always re-open.

Steve
