### ISSUE TITLE
Look for spikes in in the space outside of the head

### ISSUE THREAD

**Issue by chrisgorgo** [preprocessed-connectomes-project/quality-assessment-protocol#33]
Some researchers report checking for spikes outside of the head (in the air surrounding it) a useful measure of data quality complimentary to normal spike detection. See for example: http://www.cbi.nyu.edu/Downloads/dataQuality.pdf

This could be easily implemented by changing the mask input to 3dToutcount.

**Comment by ccraddock** [comment]
We are thinking that this would be an additional metric so that in-brain spikes could be differentiated from out-of-brain spikes.

**Comment by sgiavasis** [comment]
Implementing this in the release as OOB (Out-of-Brain) Outliers. Will discuss additional tweaks further during testing.
