### ISSUE TITLE
Pypi package does not include shebangs

### ISSUE THREAD

**Issue by chrisgorgo** [preprocessed-connectomes-project/quality-assessment-protocol#36]
For some reason the tgz package deposited on Pypi (the same one that is being used each time someone does pip install qap or easy_install qap) does not include shebangs (#!/usr/bin/env python) on top of script rendering them unusable:

```
[chrisgor@sherlock-ln01 ~]$ qap_cpac_output_sublist_generator.py
/share/PI/russpold/software/anaconda/bin/qap_cpac_output_sublist_generator.py: line 3: syntax error near unexpected token `('
/share/PI/russpold/software/anaconda/bin/qap_cpac_output_sublist_generator.py: line 3: `def run(cpac_outdir, outfile_name, qap_type, session_format):'
```

the missing shebang:

```
[chrisgor@sherlock-ln01 ~]$ head `which qap_cpac_output_sublist_generator.py`


def run(cpac_outdir, outfile_name, qap_type, session_format):

    import os
    import glob
    import yaml


    if qap_type == "anat":
```

**Comment by jpellman** [comment]
Hi Chris,

This was an issue with the code in the GitHub repository as well.  We fixed it and hope to put a patched version on Pypi soon.

**Comment by jpellman** [comment]
Hello again Chris,

The patched version of QAP is now on Pypi.

Santé!
