### ISSUE TITLE
exception when using scan_id for workflow name for BIDS

### ISSUE THREAD

**Issue by carolFrohlich** [preprocessed-connectomes-project/quality-assessment-protocol#47]
https://github.com/preprocessed-connectomes-project/quality-assessment-protocol/blob/master/qap/cli.py#L336

Using  scan_id for the workflow name doesn't work for BIDS, since scan_id will contain underscores and hyphens. The workflow name verifier will throw an exception for these .

**Comment by sgiavasis** [comment]
I'm having it replace illegal characters with underscores for now, but we should discuss solutions further.

Note: the change is in 1.0.6_dev
