### ISSUE TITLE
[BUG] CSV file for anatomical measures not created

### ISSUE THREAD

**Issue by mmayolini** [preprocessed-connectomes-project/quality-assessment-protocol#49]
When I run qap_anatomical_spatial.py, I get this as crash file : 

File: crash-20160418-111315-neuro-qap_anatomical_spatial_to_csv.pklz
Node: anat_1.qap_anatomical_spatial_to_csv
Working directory: /home/neuro/Scripts_mmayolini/output/working/001/session_1/anat_1/qap_anatomical_spatial_to_csv

Node inputs:

_outputs = {'fg_std': 80.12024679070052, 'scan': 'anat_1', 'bg_mean': 1.5794646729758111, 'fber': 1491.7785062783855, 'gm_mean': 169.21323137084809, 'csf_size': 116074, 'wm_size': 631516, 'csf_std': 66.239880645059017, 'session': 'session_1', 'csf_mean': 111.56166755690336, 'fwhm_z': 5.1265599999999996, 'fwhm': 5.4352219393378221, 'fwhm_x': 5.2217782290689065, 'subject': '001', 'gm_std': 24.938502129319794, 'bg_std': 2.2595475332396213, 'wm_mean': 233.21506660163797, 'cnr': 28.325066983223579, 'bg_size': 4412854, 'qi1': 0.2093062675538325, 'wm_std': 30.747508893546986, 'gm_size': 580998, 'fg_mean': 70.13310178976792, 'snr': 31.038560047114714, 'fwhm_y': 5.99803, 'efc': 0.49637074887380966, 'fg_size': 7121482}
ignore_exception = False
in_file = output/qap_anatomical_spatial.csv

Traceback: 
Traceback (most recent call last):
  File "/home/neuro/anaconda2/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 38, in run
    node.run(updatehash=updatehash)
  File "/home/neuro/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1428, in run
    self._run_interface()
  File "/home/neuro/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1538, in _run_interface
    self._result = self._run_command(execute)
  File "/home/neuro/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1664, in _run_command
    result = self._interface.run()
  File "/home/neuro/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1033, in run
    runtime = self._run_wrapper(runtime)
  File "/home/neuro/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 983, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home/neuro/anaconda2/lib/python2.7/site-packages/nipype/algorithms/misc.py", line 891, in _run_interface
    with open(self.inputs.in_file, 'w') as f:
IOError: [Errno 2] No such file or directory: 'output/qap_anatomical_spatial.csv'

I checked, and indeed there isn't any CSV file in my output folder. Did I forget to download or install something, or is there a bug ?

**Comment by jpellman** [comment]
Hi Maxime,

When you specify the output directory in your pipeline configuration file, are you using an absolute path or a relative path?  If you are using a relative path could you try using an absolute path instead?

If this does not work, could you send your pipeline configuration and crash files to john.pellman@childmind.org?

Best,
John Pellman

**Comment by mmayolini** [comment]
Hi John,

Output and working directories in the configuration file were specified with a relative path ; however, I have a problem using the absolute path. I give you all the details to the mail address you mentioned.

Cordially,
Maxime

EDIT : I was using "~" in the absolute path, that was the thing that didn't work (it created a folder "~" on my home) ; I replaced it with the folders it represents, and now it seems working. I'll update this post when the execution is finished to tell you if the bug remains.

EDIT 2 : It works ! Thank you very much, John ! However, I have a minor bug to report concerning the number of procs used, I tell you more in a mail.
