### ISSUE TITLE
Warn users if running config with qap_anatomical_spatial with necessary parameters undefined

### ISSUE THREAD

**Issue by jpellman** [preprocessed-connectomes-project/quality-assessment-protocol#53]
Present behavior if _template_brain_for_anat_ and _template_skull_for_anat_ are undefined is to run through pipeline without producing outputs without warning user that these parameters are not defined.

**Comment by sgiavasis** [comment]
Was this on 1.0.5 by any chance?

**Comment by sgiavasis** [comment]
Nonetheless, better config checking (and warning messages) are needed. Putting these in..
