### ISSUE TITLE
QAP 1.0.5 only works with one core

### ISSUE THREAD

**Issue by jpellman** [preprocessed-connectomes-project/quality-assessment-protocol#54]
The QAP 1.0.5 will only work if num_cores is set to 1- other integers will cause it to crash.

**Comment by hebbianloop** [comment]
also having a similar problem:

> Traceback (most recent call last):
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/qap_anatomical_spatial.py", line 16, in <module>
>     obj.run()
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qap/cli.py", line 241, in run
>     results = self._run_here(run_name)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qap/cli.py", line 184, in _run_here
>     results = pool.map(_run_workflow, wfargs)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
>     return self.map_async(func, iterable, chunksize).get()
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
>     raise self._value
> IOError: Duplicate node name datasink_qap_mosaic found.

**Comment by sgiavasis** [comment]
This has been resolved in the upcoming version. Will close when released.
