### ISSUE TITLE
[BUG] CSV file for anatomical measures not created - part 2

### ISSUE THREAD

**Issue by hebbianloop** [preprocessed-connectomes-project/quality-assessment-protocol#55]
Hi,

I followed the advice for setting absolute paths in the previous bug resolution but this did not fix the bug:

>   File "pandas/parser.pyx", line 353, in pandas.parser.TextReader.**cinit** (pandas/parser.c:3246)
>   File "pandas/parser.pyx", line 591, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:6111)
> IOError: File /Volumes/Archive.ADS/ADS/analysis/ads.qap/qap_anatomical_spatial.csv does not exist

the configuration file is as below

> num_cores_per_subject: 4
> 
> num_subjects_at_once: 6
> 
> output_directory: /Volumes/Archive.ADS/ADS/analysis/ads.qap
> 
> working_directory: /Volumes/Archive.ADS/ADS/analysis/ads.qap/working
> 
> write_all_outputs: True
> 
> template_brain_for_anat: /usr/local/fsl/data/standard/MNI152_T1_2mm_brain.nii.gz
> 
> template_skull_for_anat: /usr/local/fsl/data/standard/MNI152_T1_2mm.nii.gz
> 
> write_report: True
> 
> write_graph: True

**Comment by jpellman** [comment]
Hi @seldamat ,

Are there any files being generated in the output directory that end in '.pklz'?  These are nipype crash files that might be able to aid us in narrowing down what might have caused the crash.

**Comment by hebbianloop** [comment]
Hi John,

Thank you for your quick attention.  There are no files in the output directory that end in .pklz.

> shad@foo:/Volumes/Archive.ADS/ADS/analysis/ads.qap 👾  ls -al
> total 64K
> drwxr-xr-x   8 shad  272 Aug  2 16:06 .
> drwxr-xr-x  11 shad  374 Aug  2 16:02 ..
> -rw-r--r--   1 shad 6.1K Aug  2 15:49 .DS_Store
> drwxr-xr-x 134 shad 4.5K Aug  2 15:50 qap_config_ADS_spatial
> -rwxr-xr-x   1 shad  377 Aug  2 16:06 qap_config_ADS_spatial.yml
> -rw-r--r--   1 shad  18K Aug  2 16:06 w1-list.yml
> -rw-r--r--   1 shad  18K Aug  2 16:02 w1-list.yml-old
> drwxr-xr-x 134 shad 4.5K Aug  2 15:50 working

**Comment by jpellman** [comment]
Hi @seldamat ,

Just to verify, does the pipeline execution work after switching 'num_cores_per_subject' to just one core?  Or does that cause the 'qap_mosaic' error you posted earlier?

**Comment by hebbianloop** [comment]
Hi @jpellman 

I ran the pipeline again with 1 core per subject and 24 subjects at once and it appears to have advanced to the skull stripping stage. Hopefully it won't crash out again!

Just so you know, I've also followed the pull request to fix the duplicate problem when running multiple cores.

**Comment by sgiavasis** [comment]
Closing this issue! Re-open if we see recurrence.
