### ISSUE TITLE
[BUG] ValueError: x and y must have the same first dimension

### ISSUE THREAD

**Issue by hebbianloop** [preprocessed-connectomes-project/quality-assessment-protocol#56]
Got the following error after successfully executing the pipeline and attempting to write the reports.  Is it recommended to update sort(columns=)?

>    Writing PDF reports
> /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qap/viz/reports.py:39: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
>   columns=['subject', 'session', 'scan'])
> Traceback (most recent call last):
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/qap_anatomical_spatial.py", line 16, in <module>
>     obj.run()
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qap/cli.py", line 253, in run
>     out_dir=config['output_directory'])
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qap/viz/reports.py", line 131, in workflow_report
>     func(df, subject=subid, out_file=qc_ms)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qap/viz/reports.py", line 339, in qap_anatomical_spatial
>     out_file=out_file)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qap/viz/reports.py", line 248, in _write_report
>     title='QC measures ' + subtitle)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qap/viz/plotting.py", line 125, in plot_all
>     zorder=10)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 1813, in inner
>     return func(ax, _args, *_kwargs)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 1424, in plot
>     for line in self._get_lines(_args, *_kwargs):
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 386, in _grab_next_args
>     for seg in self._plot_args(remaining, kwargs):
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 364, in _plot_args
>     x, y = self._xy_from_xy(x, y)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 223, in _xy_from_xy
>     raise ValueError("x and y must have same first dimension")
> ValueError: x and y must have same first dimension

The config file is as follows:

> num_cores_per_subject: 1
> 
> num_subjects_at_once: 24
> 
> output_directory: /Volumes/Archive.ADS/ADS/analysis/qap
> 
> working_directory: /Volumes/Archive.ADS/ADS/analysis/qap/working
> 
> write_all_outputs: True
> 
> template_brain_for_anat: /usr/local/fsl/data/standard/MNI152_T1_2mm_brain.nii.gz
> 
> template_skull_for_anat: /usr/local/fsl/data/standard/MNI152_T1_2mm.nii.gz
> 
> write_report: True
> 
> write_graph: True

**Comment by jpellman** [comment]
Hi @seldamat ,

sort is a deprecated function in one of QAP's dependencies (pandas).  We will need to update the idiom we use with the code that employs this function in future releases.  You shouldn't need to change the version of pandas you have installed, as the error is being generated by matplotlib (another one of QAP's dependencies).

I would need to investigate this bug more deeply to fully understand why the ValueError is being generated, but in the meantime my best advice would be to leave the report writing option until we can generate a fix (apologies for the inconvenience).

**Comment by hebbianloop** [comment]
Thank  you @jpellman -- I'll look for the bug being addressed in future releases :)

So in any case, I should be able to get all of the relevant data by looking at the .csv file that's output to the output directory right?

**Comment by jpellman** [comment]
@seldamat That is correct- the csv file will contain the QAP measures for all of the subjects in your subject list.

**Comment by hebbianloop** [comment]
Hi @jpellman,

I tried running the pipeline again hoping that perhaps it would work on a second try - it didn't :\

However, it did output a .pklz file this time.  Perhaps this will be helpful for debugging? I can't seem to attach it here, so here is a google drive link:

https://drive.google.com/file/d/0B62ZUf2RblCDZk4zLXU0WTd6cWs/view?usp=sharing

**Comment by jpellman** [comment]
Hi @seldamat ,

The traceback in your crash file implicates a function from nipype being unable to append a row to your output file.  If you open the output file located at /Volumes/Archive.ADS/ADS/analysis/qap/qap_anatomical_spatial.csv, are there any odd characters at the top of the file or is the file empty?

**Comment by hebbianloop** [comment]
The file actually looks fine! no odd characters and the spreadsheet is populated with matching data.

The report summary however did report a subject failing the pipeline that did not fail when I ran it yesterday.

**Comment by jpellman** [comment]
Are there any crash files for nodes other than 'anatomical_spatial_to_csv' for that subject?

**Comment by hebbianloop** [comment]
There were no other crash files :-\ I've tried upgrading and reinstalling qap + xhtml2pdf to no avail

**Comment by jpellman** [comment]
In that case my best advice would be to toggle the 'write_report' option off for the moment.  This functionality is one of the newer additions to QAP and it isn't as reliable as the core functionality unfortunately- my apologies.  We'll continue looking into fixing this in future releases.

**Comment by hebbianloop** [comment]
thanks @jpellman -- you may find it of interest that a pdf file was actually generated, although I do not think it is the complete document
[qap_anatomical_spatial_group.pdf](https://github.com/preprocessed-connectomes-project/quality-assessment-protocol/files/405089/qap_anatomical_spatial_group.pdf)

**Comment by sgiavasis** [comment]
I was able to reproduce this error and fix it. @seldamat: At some point, I may have you try it again right before the release.

**Comment by sgiavasis** [comment]
@jpellman We should do some final runs/checks on this to make extra sure it's not still happening.
