### ISSUE TITLE
[BUG] Not all participants in subject list are being run

### ISSUE THREAD

**Issue by jpellman** [preprocessed-connectomes-project/quality-assessment-protocol#57]
@DaveOC90 Noted yesterday that for some runs, a small subset of participants were not being run.  To work around this, he created a new subject list with just the participants who weren't being run and was able to get them to run that way.

**Comment by hebbianloop** [comment]
ah I noticed this too, thanks for the heads up

**Comment by sgiavasis** [comment]
I isolated the source of this bug and fixed it in the development branch... the fix will be in the release.
