### ISSUE TITLE
QAP Anatomical Crash [TypeError in pool.py]

### ISSUE THREAD

**Issue by hebbianloop** [preprocessed-connectomes-project/quality-assessment-protocol#59]
160807-20:48:22,747 workflow INFO:
     Configuration settings:
{'write_graph': False, 'write_all_outputs': False, 'num_subjects_at_once': 24, 'output_directory': '/Volumes/Archive.ADS/ADS/analysis/qap', 'write_report': True, 'working_directory': '/Volumes/Archive.ADS/ADS/analysis/qap/werk', 'num_cores_per_subject': 1, 'template_skull_for_anat': '/usr/local/fsl/data/standard/MNI152_T1_2mm.nii.gz', 'pipeline_config_yaml': '/Volumes/Archive.ADS/ADS/analysis/qap/Anatomical.yml', 'template_brain_for_anat': '/usr/local/fsl/data/standard/MNI152_T1_2mm_brain.nii.gz', 'qap_type': 'anatomical_spatial'}
Traceback (most recent call last):
  File "/Users/shad/quality-assessment-protocol/scripts/qap_anatomical_spatial.py", line 10, in <module>
    obj.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qap/cli.py", line 244, in run
    results = self._run_here(run_name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qap/cli.py", line 187, in _run_here
    results = pool.map(_run_workflow, wfargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by sgiavasis** [comment]
Hi Seldamat,

Which version of QAP are you running?

**Comment by hebbianloop** [comment]
I used pip to install version 1.0.5 -- i've also tried building from this repo but that never seems to work for me.

**Comment by sgiavasis** [comment]
This issue should be resolved in the 1.0.6_dev_parallel branch (which is slated for an upcoming official release). I would recommend trying that version, though there have been quite a few changes since 1.0.5 - you may need to update your configuration files if you choose to do so.

The most recent format for the configuration files are available here, under the files ending with _TEMPLATE:
https://github.com/preprocessed-connectomes-project/quality-assessment-protocol/tree/1.0.6_dev_parallel/configs

If you do give it a shot, let me know if you need any assistance!

**Comment by hebbianloop** [comment]
Hi @sgiavasis,

Sure, I'd love to give it a shot to see if I can get this running on some of my data. Is the right way to install the development version?
1. Select the branch in the dropdown menu
2. Downloaded the .zip 
3. copied over all the scripts to my macports install of python

`sudo cp Downloads/quality-assessment-protocol-1.0.6_dev_parallel/scripts/* /opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/`
1. Installed the dev version

```
python setup.py -v build
python setup.py -v install
```

I'm running the pipeline now - I'll update this post with the results!

**Comment by sgiavasis** [comment]
We appreciate your willingness to help us debug/test. :D

**Comment by hebbianloop** [comment]
Of course! This is a great suite of tools for neuroimaging research so I'm happy to help out in any way I can :)

One thing I noticed is that your new template configuration files for the functional pipelines do not have the start/stop IDX nor the slice_timing_correction or ghost direction fields.  Should these be included or is it ok to leave them out?

The anatomical pipeline is still running but it appears that the segmentation step is crashing out on subjects that were successfully run in the past.  Here is a link to the pklz files and associated logs

https://drive.google.com/open?id=0B62ZUf2RblCDVjlhRjVSZ25nb28

Please let me know if you need any more information or whether you'd like me to open this up as a separate issue.

**Comment by sgiavasis** [comment]
The change in the configuration template will be reflected in the new release's documentation- sorry for the gap in info.

The start/stop IDX now defaults to 0 and End respectively, but you can override these with your own settings by including the options if you'd like (you just don't have to anymore).

Slice timing correction has been removed from QAP.

And ghost direction defaults to Y, as this is the most prevalent configuration. However, you can override this just like with the start/stop IDX by including the parameter and setting it to either X or Z if appropriate.

I'm going to take a look at those crashes in the meantime.

**Comment by sgiavasis** [comment]
Hi Seldamat,

For the run that produced those segmentation crash files-  was this a run you had started earlier, stopped, then started again? It looks like something funny might have happened in the working directory and it just can't find where to pick up from with segmentation.

I would try, at least for one of the crashed subjects, clearing out the working directory for that one subject and re-running and seeing if that crash still occurs.

Did you have any issues installing the 1.0.6_dev_parallel branch, by the way?

**Comment by hebbianloop** [comment]
Hi sgiavasis,

Yes, it was a run that I interrupted because I wanted to modify the config
file.

Since then I've reinstalled the 1.0.6_dev_parallel branch by cloning it,
building and installing and copying the scripts to my python bin path.

I deleted the directory and reran everything from scratch and I am not
getting the same error anymore.

However, I am getting a new error

Configuration settings:
{'num_subjects_per_bundle': 24, 'resource_manager': 'None', 'scan_id':
'Anat_1', 'pipeline_config_yaml':
'/Volumes/Archive.ADS/ADS/analysis/qap-testdev-2/Anatomical.yml',
'subject_id': 'J31344', 'write_all_outputs': True, 'num_bundles_at_once':
1, 'session_id': 'w1', 'output_directory':
'/Volumes/Archive.ADS/ADS/analysis/qap-testdev-2', 'write_report': False,
'working_directory':
'/Volumes/Archive.ADS/ADS/analysis/qap-testdev-2/werk',
'template_skull_for_anat':
'/usr/local/fsl/data/standard/MNI152_T1_2mm.nii.gz', 'run_name':
'Anatomical', 'template_brain_for_anat':
'/usr/local/fsl/data/standard/MNI152_T1_2mm_brain.nii.gz', 'qap_type':
'anatomical_spatial'}
Traceback (most recent call last):
  File
"/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/qap_anatomical_spatial.py",
line 10, in <module>
    obj.run()
  File
"/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qap/cli.py",
line 244, in run
    results = self._run_here(run_name)
  File
"/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qap/cli.py",
line 178, in _run_here
    results.append(_run_workflow(a))
  File
"/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qap/cli.py",
line 358, in _run_workflow
    if not op.isfile(resource_pool[resource]):
  File
"/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py",
line 37, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by sgiavasis** [comment]
How does your participant list look? First thing, I would double-check the filepaths of the "anatomical_scan" entries to see if any of them look off.

**Comment by hebbianloop** [comment]
The paths all exist, I'm 100% sure of that -- I've rerun this a bunch of times now and I keep getting the same error message. Any suggestions?

**Comment by sgiavasis** [comment]
Further up in the stream you printed above, do you have a "Contents of resource pool:" message? If you don't have the text anymore, you can also check the pypeline.log file.

**Comment by sgiavasis** [comment]
@jpellman We should do some final runs/checks on this to make extra sure it's not still happening.
