### ISSUE TITLE
Bug- all integer session ID causes PDF reports to crash

### ISSUE THREAD

**Issue by jpellman** [preprocessed-connectomes-project/quality-assessment-protocol#64]
From the [PCP forum](https://groups.google.com/forum/#!topic/pcp_forum/ncxhjc_A6oE), Jordi Huguet reports the following bug:

Minor issue found at 'qap/viz/reports.py'. If session IDs are fully composed by digits, they are treated as numpy integers and QAP crashes at composing the path tree for storing the PDF reports.

Error message prompted:

```
    Traceback (most recent call last):
      File "/opt/amc/devel/python-2.7.12/bin/qap_functional_temporal.py", line 4, in <module>
    ...
      File "/opt/amc/devel/python-2.7.12/lib/python2.7/site-packages/qap-1.0.5-py2.7.egg/qap/viz/reports.py", line 105, in workflow_report
        sub_path = op.join(out_dir, run_name, '/'.join(sub_info))
    TypeError: sequence item 1: expected string, numpy.int64 found
```

Code fragment which crashes:

```
        # Re-build mosaic location
        for sesid in sessions:
            sesdf = subdf.loc[subdf['session'] == sesid]
            scans = sorted(pd.unique(sesdf.scan.ravel()))

            # Each scan has a volume and (optional) fd plot
            for scanid in scans:
                sub_info = [subid, sesid, scanid]
                sub_path = op.join(out_dir, run_name, '/'.join(sub_info))
                m = op.join(sub_path, 'qap_mosaic', 'mosaic.pdf')
               ...
```

I temporarily fixed it by casting all 'sub_info' list items to string type before composing the directory path at the given function (workflow_report) of the script reports.py; however might require a better insight. 
`
sub_info = [str(i) for i in sub_info]
`

**Comment by sgiavasis** [comment]
This will do it- I had to do something similar for Participant IDs- probably should do it for scan IDs as well. Did you make that fix in a branch? If not, I can do it in 1.0.8.
