### ISSUE TITLE
report generation is failing due to lack of csv files

### ISSUE THREAD

**Issue by alexlicohen** [preprocessed-connectomes-project/quality-assessment-protocol#85]
The json_to_csv module does not seem to be working?

170116-22:03:59,635 workflow INFO:
	 Writing PDF reports
Traceback (most recent call last):
  File "/code/run.py", line 132, in <module>
    obj.run(config_file, subject_list_file)
  File "/usr/local/bin/miniconda/lib/python2.7/site-packages/qap-1.0.8-py2.7.egg/qap/cli.py", line 909, in run
    out_dir=config['output_directory'])
  File "/usr/local/bin/miniconda/lib/python2.7/site-packages/qap-1.0.8-py2.7.egg/qap/viz/reports.py", line 36, in workflow_report
    df = pd.read_csv(in_csv, dtype={'Participant': str}).sort(
  File "/usr/local/bin/miniconda/lib/python2.7/site-packages/pandas/io/parsers.py", line 646, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/bin/miniconda/lib/python2.7/site-packages/pandas/io/parsers.py", line 389, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/bin/miniconda/lib/python2.7/site-packages/pandas/io/parsers.py", line 730, in __init__
    self._make_engine(self.engine)
  File "/usr/local/bin/miniconda/lib/python2.7/site-packages/pandas/io/parsers.py", line 923, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/bin/miniconda/lib/python2.7/site-packages/pandas/io/parsers.py", line 1390, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 373, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4184)
  File "pandas/parser.pyx", line 667, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:8449)
IOError: File /output/output/qap_anatomical_spatial.csv does not exist

**Comment by jpellman** [comment]
Hi @alexlicohen,

Please see https://groups.google.com/d/msg/pcp_forum/hpr1AaVPn-s/g-qIPD-SGQAJ ; this looks like it might be the issue you're encountering.

**Comment by alexlicohen** [comment]
I tried locking nipype to 0.12.1 and using only 1 core. The script still runs fine without writing reports, but fails when trying to write reports because the .csv files are absent. (The json files DO contain data, though).

FYI, this is using the BIDS-App/QAP docker if you want to replicate:
I'm using: https://github.com/alexlicohen/QAP
see here for differences: https://github.com/BIDS-Apps/QAP/compare/master...alexlicohen:master

docker run -ti --rm -v /home_local/ch186161/scratch_local:/tmp -v /common/collections/ABIDE/ABIDE2-BIDS/RawData/ABIDEII-ONRC_2:/bids_dataset -v /common/collections/Analyses/ABIDE2-BIDS/derivatives/QAP/ABIDEII-ONRC_2:/output alex_bids/qap /bids_dataset /output participant --participant_label 28675

vs

docker run -ti --rm -v /home_local/ch186161/scratch_local:/tmp -v /common/collections/ABIDE/ABIDE2-BIDS/RawData/ABIDEII-ONRC_2:/bids_dataset -v /common/collections/Analyses/ABIDE2-BIDS/derivatives/QAP/ABIDEII-ONRC_2:/output alex_bids/qap --report /bids_dataset /output participant --participant_label 28675

**Comment by alexlicohen** [comment]
This is still not working for the BIDS-App, any ideas? I tried dropping the pandas module back to `pandas==0.18.1`, still no luck generating csv files and thus reports...

**Comment by jpellman** [comment]
Just to put this out here- something that strikes as odd is that you the pipeline configuration YAML in your repo specifies '/output' as the output directory, but the PDF report generation function is looking for a file in '/output/output'.  It looks like the the output directory might be getting joined together twice somewhere.

**Comment by alexlicohen** [comment]
Yes that's as I found the repo, I've been meaning to fix it but now you're making me wonder if perhaps it's the problem. I'll go through and align that and see what happens

-Alex

**Comment by jpellman** [comment]
This looks like it might be the offending line:

https://github.com/alexlicohen/QAP/blob/master/run.py#L82

Try changing this to something like:

```
c['output_directory'] = os.path.abspath(c['output_directory'])
if not os.path.exists(c['output_directory']):
     os.makedirs(c['output_directory'])
```

**Comment by alexlicohen** [comment]
The BIDS-app was creating an additional subdir layer in the /output dir... that is now fixed in my version, but the csv files are still not being generated. I'm assuming this is working for you all locally with v1.0.8? Here is the output of `pip list` from without the docker container. Are there any differences that might be related?

Package         Version    
--------------- -----------
boto3           1.4.4      
botocore        1.5.5      
cffi            1.9.1      
conda           4.3.8      
configparser    3.5.0      
cryptography    1.7.1      
cycler          0.10.0     
decorator       4.0.11     
docutils        0.13.1     
enum34          1.1.6      
funcsigs        1.0.2      
functools32     3.2.3.post2
future          0.16.0     
futures         3.0.5      
html5lib        1.0b10     
httplib2        0.9.2      
idna            2.2        
INDI-Tools      0.0.6      
ipaddress       1.0.18     
isodate         0.5.4      
jmespath        0.9.0      
lockfile        0.12.2     
lxml            3.7.2      
matplotlib      2.0.0      
mock            2.0.0      
networkx        1.11       
nibabel         2.1.0      
nipype          0.12.1     
nitime          0.7        
nose            1.3.7      
numpy           1.11.3     
olefile         0.44       
pandas          0.19.2     
pbr             1.10.0     
Pillow          4.0.0      
pip             9.0.1      
prov            1.5.0      
pyasn1          0.1.9      
pycosat         0.6.1      
pycparser       2.17       
pyOpenSSL       16.2.0     
pyparsing       2.1.10     
PyPDF2          1.26.0     
python-dateutil 2.6.0      
pytz            2016.10    
PyYAML          3.11       
qap             1.0.8      
rdflib          4.2.1      
reportlab       3.3.0      
requests        2.12.4     
s3transfer      0.1.10     
scipy           0.18.1     
seaborn         0.7.1      
setuptools      27.2.0     
simplejson      3.10.0     
six             1.10.0     
SPARQLWrapper   1.8.0      
subprocess32    3.2.7      
traits          4.6.0      
webencodings    0.5        
wheel           0.29.0     
xhtml2pdf       0.0.6      
xvfbwrapper     0.2.9

**Comment by sgiavasis** [comment]
There are some big changes in progress for this script- also moving the reports generation here since the needed CSVs will not exist yet until after this script is run.

**Comment by sgiavasis** [comment]
Hi @alexlicohen ,

In QAP 1.0.8, report generation will be completed using the group-level script (qap_jsons_to_csv.py) that is run after the initial QAP pipeline completes.

To use this script to generate reports:
usage: qap_jsons_to_csv.py [-h] [--with_group_reports] [--with_full_reports]
                           output_dir

positional arguments:
  output_dir            the main output directory of the QAP run which
                        contains the participant directories

optional arguments:
  -h, --help            show this help message and exit
  --with_group_reports  Write a summary report in PDF format.
  --with_full_reports   Write the summary report and the individual
                        participant reports as well.

FYI, we will be greatly expanding QAP's reports/visualization capabilities in the near future, so we will keep everyone posted!

**Comment by alexlicohen** [comment]
awesome. Thanks!

-Alex


----------------------------------------------------------------
Alexander Li Cohen, M.D., Ph.D.
E-mail: Alexander.Cohen2@childrens.harvard.edu (Medical/Science Email)
E-mail: alexcohen@gmail.com (Lifetime Email)
----------------------------------------------------------------
