### ISSUE TITLE
QAP incompatible with nipype 0.13

### ISSUE THREAD

**Issue by parekhpravesh** [preprocessed-connectomes-project/quality-assessment-protocol#86]
Hello,

I recently installed qap and did a few test runs with everything running smoothly. Subsequently, I installed mriqc. Since then, I have been unable to get qap to run. The following are the output error messages:

`qap_anatomical_spatial.py --sublist /home/JPJ/Parekh/Test_QAP_MRIQC/data_QAP/sub_list.yaml /home/JPJ/Parekh/Test_QAP_MRIQC/data_QAP/qap_config_abide_spatial_tmp.yml 
`
> 170123-18:08:48,554 workflow INFO:
>      There are 2 subjects in the pool
> 170123-18:08:48,617 workflow INFO:
>      Pipeline start time: 2017-01-23_18:08:48
> 170123-18:08:48,618 workflow INFO:
>      Contents of resource pool:
> {'anatomical_scan': '/home/JPJ/Parekh/Test_QAP_MRIQC/data_QAP/sub-001/session1/anat/mprage.nii.gz'}
> 170123-18:08:48,618 workflow INFO:
>      Configuration settings:
> {'write_graph': True, 'write_all_outputs': True, 'num_subjects_at_once': 1, 'output_directory': '/home/JPJ/Parekh/Out_QAP', 'write_report': False, 'working_directory': '/home/JPJ/Parekh/Work_QAP', 'num_cores_per_subject': 1, 'template_skull_for_anat': '/usr/local/fsl/data/standard/MNI152_T1_2mm.nii.gz', 'pipeline_config_yaml': '/home/JPJ/Parekh/Test_QAP_MRIQC/data_QAP/qap_config_abide_spatial_tmp.yml', 'template_brain_for_anat': '/usr/local/fsl/data/standard/MNI152_T1_2mm_brain.nii.gz', 'qap_type': 'anatomical_spatial'}
> Traceback (most recent call last):
>   File "/home/JPJ/Enthought/Canopy_64bit/User/bin/qap_anatomical_spatial.py", line 16, in <module>
>     obj.run()
>   File "/home/JPJ/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/qap/cli.py", line 244, in run
>     results = self._run_here(run_name)
>   File "/home/JPJ/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/qap/cli.py", line 178, in _run_here
>     results.append(_run_workflow(a))
>   File "/home/JPJ/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/qap/cli.py", line 375, in _run_workflow
>     workflow, resource_pool = wf_builder(workflow, resource_pool, config)
>   File "/home/JPJ/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/qap/qap_workflows.py", line 183, in qap_anatomical_spatial_workflow
>     qap_mask_workflow(workflow, resource_pool, config)
>   File "/home/JPJ/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/qap/qap_workflows.py", line 40, in qap_mask_workflow
>     config)
>   File "/home/JPJ/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/qap/anatomical_preproc.py", line 257, in flirt_anatomical_linear_registration
>     anatomical_skullstrip_workflow(workflow, resource_pool, config)
>   File "/home/JPJ/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/qap/anatomical_preproc.py", line 126, in anatomical_skullstrip_workflow
>     anatomical_reorient_workflow(workflow, resource_pool, config)
>   File "/home/JPJ/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/qap/anatomical_preproc.py", line 26, in anatomical_reorient_workflow
>     anat_deoblique = pe.Node(interface=preprocess.Refit(),
> **AttributeError: 'module' object has no attribute 'Refit'**

Please advise on how to proceed to resolve this error. Thanks a lot in advance!

Thanks and Regards
Pravesh Parekh

**Comment by jpellman** [comment]
Hi @parekhpravesh ,

It looks like installing mriqc may have upgraded your version of nipype to a version that is not compatible with QAP.  If you open a Python prompt and type the following commands, does Python print '0.13.0-rc1'?

```
import nipype
print nipype.__version__
```

If Python does print that version number, you should be able to get QAP working by typing the following command to downgrade nipype to a QAP-compatible version:

`pip install nipype==0.12.1`

**Comment by parekhpravesh** [comment]
Hello,

Thanks for the reply. As predicted, nipype is actually version 0.13.0-rc1 (I believe this is the version required by mriqc). That makes mriqc and qap (almost) mutually exclusive!

**Comment by ccraddock** [comment]
Yes. We haven't updated to nipype 13 yet since it is still a release candidate and not an official release. You should be able to handle two versions of nipype with virtual environments.

**Comment by parekhpravesh** [comment]
Thank you Dr. @ccraddock...virtual environment it is then!
